
version: 2

models:
  - name: bookings_dbt
    description: "Sample data of Airports"
    columns:
      - name: booking_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: bookings_raw

