
version: 2

models:
  - name: cleaned_airports
    description: "Sample data of Airports"
    columns:
      - name: airport_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: airports_raw

